version: '3.8'

services:
  webapi:
    environment:
      - ASPNETCORE_URLS="https://0.0.0.0:4343;http://0.0.0.0:8088"
      - ASPNETCORE_Kestrel__Certificates__Default__Password="123"
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_ENVIRONMENT=Development
      - LOG_FOLDER=/app/logs
    ports:
      - "8088:8088"
      - "4343:4343"
    volumes:
      - "aspnet-secrets:/https/"
      - "log-folder:/app/logs"

  logreader:
    environment:
      - LOG_FOLDER=/app/logs
    volumes:
      - "log-folder:/app/logs"

volumes:
  log-folder:
    driver: local
    driver_opts:
        o: 'bind' 
        device: "c/Users/root/.aspnet/Logs"
        type: none
  aspnet-secrets:
    driver: local
    driver_opts:
      o: 'bind' 
      device: "c/Users/root/.aspnet/https"
      type: none